### PR TITLE
set dependencies uuids on flow/operation ExecutionPlan

### PR DESCRIPTION
**Pull request by shajyhia**
before return CompilationArtifact get executionPalne and populate SubflowsUUIDs:
executionPlan.setSubflowsUUIDs(new HashSet<>(dependencies.keySet()));

### CODE REVIEW

**Comment by shajyhia** [comment]
before return CompilationArtifact get executionPalne and populate SubflowsUUIDs:
executionPlan.setSubflowsUUIDs(new HashSet<>(dependencies.keySet()));

**Comment by meirwah** [comment]
not sure dependencies.keySet() is the same as SubflowsUUIDs...
dependencies can also be operations? @orius123 correct me if i'm wrong...

**Comment by orius123** [comment]
It's correct for AFL, we need to change the field name in execution plan to dependecies.

**Comment by meirwah** [comment]
@shajyhia you need to update branch.. since we can not merge this automatically

**Comment by meirwah** [comment]
@shajyhia  why do you need this commit?
what does it do in OO?

**Comment by oritstone** [comment]
Committed the change to the master

**Pull request closed without merging**
