### PR TITLE
System properties

### PR DESCRIPTION
**Pull request by avimora**

### CODE REVIEW

**Comment by meirwah** [comment]
"systemProperties" in the yaml file? is this our convention?

**Comment by avimora** [comment]
Well... that's one of the reasons I didn't like the term... don't like it either...
Imposed by the yaml parser, it has to be identical to the java member name...
Suggestions?

**Comment by orius123** [comment]
Didn't we decided something after all of the mails about it? was it systemProperties??
I don't think that this is a good functional name, and if the yamlParser is the problem we should handle it somehow.

**Comment by meshipeer** [comment]
we agree on system properties
and as i comment to the FS: i think it should be system_properties in the DSL

**Comment by avimora** [comment]
So we go with `system_properties` and `system_property`? should I try to figure a workaround for the parser?

**Comment by avimora** [comment]
@meirwah, @orius123, @meshipeer, @oritstone can you please review & merge?

**Pull request merged**
