### PR TITLE
NPM - A new way of getting the score command line interface.

### PR DESCRIPTION
**Pull request by dorsha**
I’ve created and published an NPM package for score-cli.

GIT repository:
https://github.com/dorsha/score-cli

The NPM package page in the NPM repository:
https://www.npmjs.com/package/score-cli

So getting score has never been so easy! Just run in your command line:
npm install -g score-cli
(It might take a while in the HP network…)

And then you can just use ‘score’ command anywhere on your system:
score

### CODE REVIEW

**Comment by meirwah** [comment]
:+1:

**Comment by orius123** [comment]
Add java to pre requisites. 
60 downloads??

**Comment by dorsha** [comment]
Will add Java.
Not sure how it got to 60 download.... odd

**Comment by meirwah** [comment]
@orius123  can we merge this?

**Comment by orius123** [comment]
If the readme looks fine to you. Go ahead :wink:

**Pull request merged**
