### PR TITLE
jackson annotations

### PR DESCRIPTION
**Pull request by orius123**
added jackson annotations to support deserializing immutable classes with custom constructor.

### CODE REVIEW

**Comment by orius123** [comment]
@shajyhia please review and let me know if it solve the issue for you

**Comment by shajyhia** [comment]
do you have a release?

**Comment by orius123** [comment]
no.
want to make sure it helps you first.
if it doesn't we will try another path.

**Comment by shajyhia** [comment]
works fine

**Comment by meirwah** [comment]
:+1:

**Pull request merged**
