### PR TITLE
zip slang cli

### PR DESCRIPTION
**Pull request by orius123**

### CODE REVIEW

**Comment by orius123** [comment]
@meirwah please check that it works on windows and merge

**Comment by meirwah** [comment]
:+1:

**Comment by orius123** [comment]
unix permissions doesn't work when zipping on windows

**Comment by orius123** [comment]
keeping open until we will package slang-content in the zip

**Comment by meirwah** [comment]
Maybe @hararzafrir can help to build a post release script (github hook) to create the Zip ?

**Comment by hararzafrir** [comment]
The hooks cannot work because our build system is not exposed to GitHub... I cannot provide GitHub with a URL on our Jenkins :-(

**Comment by meirwah** [comment]
can we put a hook to Travis or another CI/CD soultion ? to upload artifacrt?

**Comment by hararzafrir** [comment]
I have a task to prepare that zip file as we discussed, I hope to make progress with it soon

**Pull request closed without merging**
