### PR TITLE
Add system test support to content verifier

### PR DESCRIPTION
**Pull request by oritstone**

### CODE REVIEW

**Comment by oritstone** [comment]
**Spec:**
- All slang content system tests will reside in slang-content repo under: *slang-content/test* dir
- All tests for a flow with the namespace a.b.c will reside in the directory: *slang-content/test/a/b/c*
- A test case will be a composition of an executable *.sl* file and a yaml file containing inputs & description
-

**Tasks**:
- [ ] Pack Slang runtime in the content verifier jar
- [ ]

**Comment by oritstone** [comment]
**Tasks**:
- [ ] Pack Slang runtime in the content verifier jar
- [ ]

**Comment by meirwah** [comment]
@oritstone what with negative tests (where we want to validate flow failed)
and we need some flag , for tests that need real Docker env (like pre-requiest)...

**Comment by oritstone** [comment]
@meirwah good points.
I added to the spec above also the notion of test suites, in order to allow for running only the base test suite, or add, for example, running also Docker tests (if we have an env for it).
I also added to the spec support in system properties

**Comment by meshipeer** [comment]
looks good - i dont sure i understand how you know which flow should run...

**Comment by oritstone** [comment]
@meshipeer 
- For each test case there is a  test suite specified. If no test suite is specified, it means general.
When running the build tool (verifier) it will run all test cases in the general+ test suites that are given as a prameter.
- The name of the test cases file has a convention that it is identical to the name of the test flow to run + the *.inputs.yaml* extension. 

Does it answer your question?

**Comment by meshipeer** [comment]
yes 10x

**Comment by orius123** [comment]
@oritstone please see my latest changes and merge.

**Pull request merged**
