### PR TITLE
Transformers shouldn't run for keys that does not exist

### PR DESCRIPTION
**Pull request by orius123**
Signed-off-by: Eliya Sadan <eliyasadan@gmail.com>

### CODE REVIEW

**Comment by orius123** [comment]
@oritstone WDYT on this approach?
can't merge because tests fail..

**Comment by oritstone** [comment]
I think it is OK. This way we don't get unused keys with null values. Also, it might prevent bug in some cases (null pointer exceptions in the transformers)

**Comment by orius123** [comment]
ok cool.
so we need to fix the failing tests.

**Comment by orius123** [comment]
@oritstone pls merge

**Pull request merged**
