### PR TITLE
added score social networks action dependency Signed-off-by: Ioan Vranau ioan.vranau@hp.com

### PR DESCRIPTION
**Pull request by ioanvranau**
... ioan.vranau@hp.com

### CODE REVIEW

**Comment by meirwah** [comment]
when adding a new action.. you must publish in on maven cetral before you can promote it to slang..
this is why the Travis CI fails...

**Comment by ioanvranauhp** [comment]
I commited yesterday after hackaton because I understood that we need to commit in a branch all our work. And yes we need somebody to help us to publish into maven central.

**Comment by meirwah** [comment]
ok

**Comment by oritstone** [comment]
Developed during the Hackathon. 
It is a great story, but we decided not to merge it

**Pull request closed without merging**
